// personal-portfolio/components/CardCta.jsx
'use client'

import { CTA_ARROW_SVG } from '@/lib/cardCta'

export default function CardCta({ label = 'View' }) {
  return (
    <div className="card-cta" aria-hidden="true">
      <div className="card-cta__scale">
        <span className="card-cta__pill">{label}</span>
        <span className="card-cta__arrow" dangerouslySetInnerHTML={{ __html: CTA_ARROW_SVG }} />
      </div>
    </div>
  )
}

// personal-portfolio/src/components/CardCta.vue
<template>
  <div class="card-cta" aria-hidden="true">
    <div class="card-cta__scale">
      <span class="card-cta__pill">{{ label }}</span>
      <span class="card-cta__arrow" v-html="arrowSvg" />
    </div>
  </div>
</template>

<script>
import { CTA_ARROW_SVG } from '../utils/cardCta.js'

export default {
  name: 'CardCta',
  props: {
    label: {
      type: String,
      default: 'View'
    }
  },
  data() {
    return {
      arrowSvg: CTA_ARROW_SVG
    }
  }
}
</script>
